"""
Operational timeline generator.

Produces a chronological markdown timeline of infrastructure evolution
across multiple operational snapshots.

Groups events by date. Each entry describes what changed from the
previous snapshot. Useful for understanding the operational narrative:
when providers appeared, when workflows emerged, when architecture shifted.

Advisory output only. Read-only reconstruction from snapshot history.
"""

from __future__ import annotations

import logging
from datetime import UTC, datetime
from typing import Any

from cognition.temporal_analysis import TemporalAnalysis, _compare_snapshots

logger = logging.getLogger(__name__)


def generate_timeline(
    snapshots: list[dict[str, Any]],
    temporal: TemporalAnalysis | None = None,
) -> str:
    """Generate a markdown operational timeline from a list of snapshots.

    snapshots: sorted oldest → newest. Each has id, created_at, data.
    """
    if not snapshots:
        return "# Operational Timeline\n\n_No snapshot history available._\n"

    lines: list[str] = [
        "# Operational Timeline",
        f"**Generated:** {_now()}",
        f"**Snapshots:** {len(snapshots)}",
        "",
    ]

    if temporal:
        lines += [
            "## Summary",
            f"- **Analysis window:** {temporal.window_days} days",
            f"- **Total changes detected:** {temporal.total_changes}",
            f"- **Volatility score:** {temporal.volatility_score:.2f} "
            f"(stability: {temporal.stability_score:.2f})",
            "",
        ]
        if temporal.churn_indicators:
            lines.append("**Key indicators:**")
            for ind in temporal.churn_indicators:
                lines.append(f"- {ind}")
            lines.append("")

    lines.append("---")
    lines.append("")

    # Build events per snapshot
    events_by_snapshot: dict[int, list[str]] = {}

    for i, snap in enumerate(snapshots):
        snap_id = snap.get("id", i)
        events_by_snapshot[snap_id] = []

        if i == 0:
            data = snap.get("data", {})
            repo = data.get("scanner_results", {}).get("results", {}).get("repo_scanner", {})
            llm_dets = data.get("llm_detections", [])
            topology = data.get("topology", {})
            workflows = data.get("workflows", [])

            if llm_dets:
                providers = [d["provider"] for d in llm_dets]
                events_by_snapshot[snap_id].append(f"Initial LLM providers: {', '.join(providers)}")
            if repo.get("frameworks"):
                events_by_snapshot[snap_id].append(
                    f"Initial frameworks: {', '.join(repo['frameworks'])}"
                )
            if topology:
                events_by_snapshot[snap_id].append(
                    f"Initial topology: {topology.get('node_count', 0)} nodes, "
                    f"{topology.get('edge_count', 0)} edges"
                )
            if workflows:
                wf_names = [w.get("name", w.get("workflow_type", "?")) for w in workflows]
                events_by_snapshot[snap_id].append(
                    f"Workflow patterns: {', '.join(wf_names)}"
                )
            if not events_by_snapshot[snap_id]:
                events_by_snapshot[snap_id].append("Initial scan — baseline established")
        else:
            change_events = _compare_snapshots(snapshots[i - 1], snap)
            for ev in change_events:
                events_by_snapshot[snap_id].append(_format_change(ev.change_type, ev.value))
            if not change_events:
                events_by_snapshot[snap_id].append("No changes from previous scan")

    # Group by date
    dates: dict[str, list[tuple[dict[str, Any], list[str]]]] = {}
    for snap in snapshots:
        created_at = snap.get("created_at", "")
        date_str = created_at[:10] if created_at else "unknown"
        dates.setdefault(date_str, []).append(
            (snap, events_by_snapshot.get(snap.get("id", 0), []))
        )

    for date_str in sorted(dates.keys()):
        lines.append(f"## {date_str}")
        lines.append("")
        for snap, snap_events in dates[date_str]:
            snap_id = snap.get("id", "?")
            created_at = snap.get("created_at", "")
            time_str = created_at[11:16] if len(created_at) >= 16 else ""
            header = f"### Snapshot #{snap_id}"
            if time_str:
                header += f" — {time_str} UTC"
            lines.append(header)
            for ev in snap_events:
                lines.append(f"- {ev}")
            lines.append("")

    lines += [
        "---",
        "*Advisory only — all operational decisions require human review.*",
        "*Generated by Quartermaster — Observe automatically. Decide manually.*",
    ]

    return "\n".join(lines)


def generate_volatility_report(temporal: TemporalAnalysis) -> str:
    """Generate a markdown volatility and stability report."""
    lines: list[str] = [
        "# Volatility & Stability Report",
        f"**Generated:** {_now()}",
        f"**Analysis window:** {temporal.window_days} days",
        f"**Snapshots analyzed:** {temporal.snapshot_count}",
        "",
        "## Scores",
        "| Metric | Score |",
        "|--------|-------|",
        f"| Volatility | {temporal.volatility_score:.3f} |",
        f"| Stability | {temporal.stability_score:.3f} |",
        f"| Total changes | {temporal.total_changes} |",
        "",
    ]

    if temporal.churning_components:
        lines += ["## Volatile Components", ""]
        lines.append("| Component | Changes | Types |")
        lines.append("|-----------|---------|-------|")
        for c in temporal.churning_components:
            lines.append(f"| {c.component} | {c.change_count} | {', '.join(c.change_types)} |")
        lines.append("")

    if temporal.churn_indicators:
        lines += ["## Churn Indicators", ""]
        for ind in temporal.churn_indicators:
            lines.append(f"- {ind}")
        lines.append("")

    if temporal.change_frequency:
        lines += ["## Change Frequency", ""]
        lines.append("| Change Type | Count |")
        lines.append("|-------------|-------|")
        for change_type, count in sorted(
            temporal.change_frequency.items(), key=lambda x: -x[1]
        ):
            lines.append(f"| {change_type} | {count} |")
        lines.append("")

    if temporal.trend_observations:
        lines += ["## Trend Observations", ""]
        for obs in temporal.trend_observations:
            lines.append(f"- {obs}")
        lines.append("")

    lines += [
        "---",
        "*Advisory only — all operational decisions require human review.*",
        "*Generated by Quartermaster*",
    ]

    return "\n".join(lines)


def generate_priority_report(
    priority_items: list[dict[str, Any]],
    temporal: TemporalAnalysis | None = None,
) -> str:
    """Generate a markdown priority report from ranked operational insights."""
    lines: list[str] = [
        "# Operational Priority Report",
        f"**Generated:** {_now()}",
        f"**Items ranked:** {len(priority_items)}",
        "",
    ]

    if not priority_items:
        lines += ["_No operational concerns requiring prioritization._", ""]
    else:
        critical = [i for i in priority_items if i.get("urgency") == "critical"]
        high = [i for i in priority_items if i.get("urgency") == "high"]
        medium = [i for i in priority_items if i.get("urgency") == "medium"]
        other = [i for i in priority_items if i.get("urgency") not in ("critical", "high", "medium")]

        for urgency_label, items, icon in [
            ("Critical", critical, "🔴"),
            ("High Priority", high, "🟠"),
            ("Medium Priority", medium, "🟡"),
            ("Low / Informational", other, "🔵"),
        ]:
            if not items:
                continue
            lines += [f"## {icon} {urgency_label}", ""]
            for item in items:
                lines.append(f"### {item.get('rank', '?')}. {item.get('title', '?')}")
                lines.append(
                    f"**Category:** {item.get('category', '?')} | "
                    f"**Score:** {item.get('priority_score', 0):.3f}"
                )
                lines.append("")
                lines.append(item.get("summary", ""))
                evidence = item.get("evidence", [])
                if evidence:
                    lines.append("")
                    lines.append("**Evidence:**")
                    for ev in evidence:
                        lines.append(f"- {ev}")
                reasoning = item.get("reasoning", [])
                if reasoning:
                    lines.append("")
                    lines.append("**Scoring reasoning:** " + " | ".join(reasoning))
                lines.append("")

    if temporal and temporal.churn_indicators:
        lines += ["## Temporal Context", ""]
        for ind in temporal.churn_indicators:
            lines.append(f"- {ind}")
        lines.append("")

    lines += [
        "---",
        "*Advisory only — all operational decisions require human review.*",
        "*Generated by Quartermaster — Observe automatically. Decide manually.*",
    ]

    return "\n".join(lines)


def generate_attention_report_md(attention_dict: dict[str, Any]) -> str:
    """Generate a markdown attention guidance report."""
    lines: list[str] = [
        "# Operational Attention Report",
        f"**Generated:** {attention_dict.get('generated_at', _now())}",
        "",
        f"> {attention_dict.get('attention_summary', '')}",
        "",
    ]

    suppressed = attention_dict.get("suppressed_count", 0)
    if suppressed:
        lines.append(f"*{suppressed} low-signal item(s) suppressed.*")
        lines.append("")

    for section_key, label, icon in [
        ("top_concerns", "Top Concerns", "🎯"),
        ("cost_concerns", "Cost Concerns", "💰"),
        ("stability_concerns", "Stability Concerns", "⚠️"),
        ("drift_concerns", "Drift Concerns", "📈"),
    ]:
        items = attention_dict.get(section_key, [])
        if not items:
            continue
        lines += [f"## {icon} {label}", ""]
        for item in items:
            urgency = item.get("urgency", "low")
            lines.append(f"### [{urgency.upper()}] {item.get('title', '?')}")
            lines.append(item.get("summary", ""))
            evidence = item.get("evidence", [])
            if evidence:
                lines.append("")
                for ev in evidence:
                    lines.append(f"- {ev}")
            lines.append("")

    lines += [
        "---",
        "*Advisory only — all operational decisions require human review.*",
        "*Generated by Quartermaster — Observe automatically. Decide manually.*",
    ]

    return "\n".join(lines)


def add_runtime_events_to_timeline(
    timeline_lines: list[str],
    runtime_health: dict[str, Any],
    snapshot_id: int | str,
    timestamp: str,
) -> list[str]:
    """Append runtime health events to a timeline line list.

    Inserts runtime instability signals and resource pressure as timeline
    entries for the given snapshot. Non-mutating — returns a new list.
    """
    lines = list(timeline_lines)
    overall = runtime_health.get("overall_status", "unknown")
    if overall in ("healthy", "unknown"):
        return lines

    time_str = timestamp[11:16] if len(timestamp) >= 16 else ""
    header = f"### Runtime Event — Snapshot #{snapshot_id}"
    if time_str:
        header += f" ({time_str} UTC)"
    lines.append(header)

    lines.append(f"- Runtime status: **{overall}** (score: {runtime_health.get('health_score', 0.0):.2f})")
    for sig in runtime_health.get("instability_signals", [])[:3]:
        lines.append(f"- {sig}")
    for rp in runtime_health.get("resource_pressure", [])[:2]:
        lines.append(f"- {rp}")
    lines.append("")

    return lines


def _format_change(change_type: str, value: str) -> str:
    labels = {
        "llm_provider_added": f"LLM provider added: **{value}**",
        "llm_provider_removed": f"LLM provider removed: **{value}**",
        "llm_sdk_added": f"LLM SDK added to packages: **{value}**",
        "llm_sdk_removed": f"LLM SDK removed from packages: **{value}**",
        "framework_added": f"Framework added: **{value}**",
        "framework_removed": f"Framework removed: **{value}**",
        "docker_added": "Docker configuration added",
        "docker_removed": "Docker configuration removed",
        "ci_added": f"CI/CD system added: **{value}**",
        "ci_removed": f"CI/CD system removed: **{value}**",
        "language_changed": f"Primary language changed: {value}",
        "workflow_type_added": f"Workflow pattern emerged: **{value}**",
        "workflow_type_removed": f"Workflow pattern no longer detected: **{value}**",
        "runtime_status_changed": f"Runtime status changed: {value}",
    }
    return labels.get(change_type, f"{change_type}: {value}")


def _now() -> str:
    return datetime.now(UTC).strftime("%Y-%m-%d %H:%M:%S UTC")
