#!/usr/bin/env python3
"""LLM meaning-layer drafter (step 2 — the one non-deterministic, on-demand step).

Reads the deterministic pass output (config/proposed_meaning.yml), the operator
meaning layer (config/operational_graph.yml), and the graph edges in graph_store,
then asks an LLM to DRAFT the residual unknowns:

  - owner_facing for every still-unknown node,
  - consequences for the consequence-less nodes,
  - upgrades of mechanical "no {filepath}" skeletons into operational meaning.

Every output is source="llm_draft", status="draft" — INERT. Nothing goes live.
The operator confirms drafts and copies accepted entries into operational_graph.yml
(then re-runs scripts/load_operational_graph.py — the existing write path).

This script writes ONLY the draft artifacts. It never writes graph_store and never
touches confirmed entries.

API KEY: read from the environment ONLY (OPENAI_API_KEY). Never hardcoded, never
logged, never written to any artifact.

Usage:
  python scripts/draft_meaning_layer.py                 # call the LLM, write drafts
  python scripts/draft_meaning_layer.py --dry-run       # assemble + print prompts, NO API call
  python scripts/draft_meaning_layer.py --model gpt-4o  # override model
"""

from __future__ import annotations

import argparse
import json
import logging
import os
import sys
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))
os.chdir(PROJECT_ROOT)

import requests  # noqa: E402
import yaml  # noqa: E402

from cognition.meaning_confirmation import rejection_keys_from_doc  # noqa: E402
from cognition.meaning_drafter import (  # noqa: E402
    DraftReport,
    assemble_facts,
    build_prompt,
    draft,
)
from memory.graph_store import GraphStore  # noqa: E402

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
log = logging.getLogger("draft_meaning_layer")

_DB_PATH = str(PROJECT_ROOT / "data" / "operational_memory.db")
_OPERATIONAL_GRAPH = PROJECT_ROOT / "config" / "operational_graph.yml"
_PROPOSED = PROJECT_ROOT / "config" / "proposed_meaning.yml"
_REJECTIONS = PROJECT_ROOT / "config" / "meaning_rejections.yml"
_OUT_YAML = PROJECT_ROOT / "config" / "drafted_meaning.yml"
_OUT_MD = PROJECT_ROOT / "reports" / "meaning_layer" / "drafted_review.md"

_KEY_ENV = "OPENAI_API_KEY"
_DEFAULT_MODEL = "gpt-4o-mini"
_API_URL = "https://api.openai.com/v1/chat/completions"

_YAML_HEADER = (
    "# Drafted meaning-layer entries — LLM DRAFTER (step 2, non-deterministic)\n"
    "# =====================================================================\n"
    "# Generated by scripts/draft_meaning_layer.py. Every entry is\n"
    "# source=\"llm_draft\", status=\"draft\" — INERT. These are grounded HYPOTHESES\n"
    "# for a human to verify, NOT active meaning. Nothing here is live until the\n"
    "# operator confirms it and copies the accepted entries into\n"
    "# config/operational_graph.yml (then re-runs load_operational_graph.py).\n"
    "#\n"
    "# Confirmed entries and the database were NOT touched. owner_facing=uncertain\n"
    "# and consequence verdict=cannot_determine are honest 'needs a human' answers.\n"
)


def _load_yaml(path: Path) -> dict[str, Any]:
    if not path.exists():
        raise FileNotFoundError(f"required input not found: {path}")
    return yaml.safe_load(path.read_text(encoding="utf-8")) or {}


def _make_openai_llm_fn(model: str):
    """Build the real LLM call. Reads the key from env only; never logs it."""
    key = os.environ.get(_KEY_ENV, "").strip()
    if not key:
        raise SystemExit(
            f"{_KEY_ENV} is not set in the environment. This drafter reads the API "
            f"key from env only. Export it (post-rotation EnvironmentFile) and retry."
        )

    def _call(system: str, user: str) -> dict[str, Any]:
        resp = requests.post(
            _API_URL,
            headers={"Authorization": f"Bearer {key}", "Content-Type": "application/json"},
            json={
                "model": model,
                "temperature": 0,  # maximise determinism for a bounded drafting task
                "response_format": {"type": "json_object"},
                "messages": [
                    {"role": "system", "content": system},
                    {"role": "user", "content": user},
                ],
            },
            timeout=60,
        )
        resp.raise_for_status()
        content = resp.json()["choices"][0]["message"]["content"]
        return json.loads(content)

    return _call


def _build_yaml_doc(report: DraftReport, generated_at: str) -> dict[str, Any]:
    nodes_out = []
    for n in report.nodes:
        if not n.drafts and not n.errors:
            continue
        nodes_out.append(
            {
                "id": n.builder_node_id,
                "target": n.target_id,
                "drafts": {d.field: d.to_dict() for d in n.drafts},
                "facts_shown": n.facts_shown,
                "errors": n.errors,
            }
        )
    return {
        "version": "1",
        "generated_at": generated_at,
        "generated_by": "scripts/draft_meaning_layer.py",
        "pass": "llm_draft",
        "model": report.model,
        "summary": report.summary(),
        "nodes": nodes_out,
    }


def _build_markdown(report: DraftReport, generated_at: str) -> str:
    s = report.summary()
    out: list[str] = []
    out.append("# Meaning-Layer Drafts — LLM Drafter (step 2, non-deterministic)")
    out.append("")
    out.append(f"_Generated {generated_at} · model `{s['model']}` · "
               "`scripts/draft_meaning_layer.py`._")
    out.append("")
    out.append(
        "Every draft below is an **inert hypothesis** (`source=llm_draft`, "
        "`status=draft`) for a human to verify — reasoned only from the cited facts. "
        "Nothing is active until you confirm it and copy it into "
        "`config/operational_graph.yml`. `uncertain` / `cannot_determine` are honest "
        "answers, not failures. Confirmed entries and the database were not touched."
    )
    out.append("")
    out.append("## Summary")
    out.append("")
    out.append(f"- Nodes drafted: **{s['nodes_drafted']}**")
    out.append(f"- owner_facing drafts: **{s['owner_facing_drafts']}** "
               f"(uncertain: {s['owner_facing_uncertain']})")
    out.append(f"- consequence drafts: **{s['consequence_drafts']}** "
               f"(cannot_determine: {s['consequence_cannot_determine']})")
    out.append(f"- parse/validation errors: **{s['errors']}**")
    out.append("")
    out.append("## Per node")
    out.append("")
    for n in report.nodes:
        out.append(f"### `{n.builder_node_id}`  ·  target `{n.target_id}`")
        out.append("")
        if n.drafts:
            for d in n.drafts:
                head = d.verdict if d.field == "owner_facing" else f"{d.verdict}"
                out.append(f"- **{d.field}** → `{head}` (confidence {d.confidence:.2f})")
                if d.value:
                    out.append(f"  - value: `{d.value}`")
                out.append(f"  - reasoning: {d.reasoning}")
                if d.facts_used:
                    out.append(f"  - facts used: {' ; '.join(d.facts_used)}")
        else:
            out.append("_No drafts produced._")
        if n.errors:
            out.append(f"- ⚠️ errors: {'; '.join(n.errors)}")
        out.append("")
        out.append("<details><summary>facts shown to the model</summary>")
        out.append("")
        for f in n.facts_shown:
            out.append(f"- {f}")
        out.append("")
        out.append("</details>")
        out.append("")
    return "\n".join(out) + "\n"


def run(dry_run: bool = False, model: str = _DEFAULT_MODEL, db_path: str = _DB_PATH) -> DraftReport:
    operational_graph = _load_yaml(_OPERATIONAL_GRAPH)
    proposed = _load_yaml(_PROPOSED)

    store = GraphStore(db_path)
    store.connect()
    try:
        nodes = store.get_active_nodes()
        edges = store.get_active_edges()
    finally:
        store.disconnect()
    label_of = {n.get("node_id", ""): n.get("builder_node_id", "") for n in nodes}

    rejection_keys = rejection_keys_from_doc(_load_yaml(_REJECTIONS))
    facts_list = assemble_facts(operational_graph, proposed, edges, label_of,
                                rejection_keys=rejection_keys)
    log.info("Assembled facts for %d node(s) needing drafts%s", len(facts_list),
             f" ({len(rejection_keys)} previously-rejected slot(s) skipped)" if rejection_keys else "")

    if dry_run:
        for nf in facts_list:
            need = [f for f, on in (("owner_facing", nf.needs_owner_facing),
                                    ("consequence", nf.needs_consequence)) if on]
            _system, user = build_prompt(nf)
            log.info("[DRY-RUN] %s needs %s", nf.builder_node_id, need)
            print(f"\n----- PROMPT for {nf.builder_node_id} -----\n{user}\n")
        return DraftReport(model=model, nodes=[])

    llm_fn = _make_openai_llm_fn(model)
    report = draft(facts_list, llm_fn, model=model)
    s = report.summary()
    log.info(
        "Drafted: %d nodes; owner_facing=%d (uncertain %d); consequence=%d "
        "(cannot_determine %d); errors=%d",
        s["nodes_drafted"], s["owner_facing_drafts"], s["owner_facing_uncertain"],
        s["consequence_drafts"], s["consequence_cannot_determine"], s["errors"],
    )

    generated_at = datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")
    _OUT_YAML.parent.mkdir(parents=True, exist_ok=True)
    with _OUT_YAML.open("w", encoding="utf-8") as f:
        f.write(_YAML_HEADER)
        yaml.safe_dump(_build_yaml_doc(report, generated_at), f,
                       sort_keys=False, default_flow_style=False, allow_unicode=True)
    log.info("Wrote %s", _OUT_YAML.relative_to(PROJECT_ROOT))

    _OUT_MD.parent.mkdir(parents=True, exist_ok=True)
    _OUT_MD.write_text(_build_markdown(report, generated_at), encoding="utf-8")
    log.info("Wrote %s", _OUT_MD.relative_to(PROJECT_ROOT))
    return report


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dry-run", action="store_true",
                        help="Assemble facts and print prompts; make NO API call")
    parser.add_argument("--model", default=os.environ.get("QM_DRAFTER_MODEL", _DEFAULT_MODEL),
                        help=f"LLM model (default {_DEFAULT_MODEL}, or $QM_DRAFTER_MODEL)")
    parser.add_argument("--db", default=_DB_PATH, help="graph_store sqlite path")
    args = parser.parse_args()
    run(dry_run=args.dry_run, model=args.model, db_path=args.db)


if __name__ == "__main__":
    main()
