#!/usr/bin/env python3
"""Deterministic meaning-layer proposal pass (step 1 — no LLM).

Reads the observed facts already persisted in graph_store (active nodes, edges,
and operator annotations) and PROPOSES the meaning-layer entries those facts can
support — produces / consequence, plus a liveness cross-check for open slots.
Everything else is left ``unknown`` for the LLM/human pass that runs after this.

This is strictly advisory. It writes NOTHING to graph_store and NOTHING to
config/operational_graph.yml. It emits two inert artifacts:

  config/proposed_meaning.yml                 — machine-readable handoff. Every
                                                entry is source="derived",
                                                status="proposed". The LLM drafter
                                                (next prompt) runs on this file.
  reports/meaning_layer/derived_proposals.md  — human review list: per node, what
                                                was proposed (with evidence) and
                                                what stays unknown.

Proposals are inert until the operator confirms them and copies the accepted ones
into operational_graph.yml — the human-confirmed source of truth.

Usage:
  python scripts/propose_meaning_layer.py             # write both artifacts
  python scripts/propose_meaning_layer.py --dry-run   # print summary, write nothing
"""

from __future__ import annotations

import argparse
import logging
import os
import sys
from datetime import UTC, datetime
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))
os.chdir(PROJECT_ROOT)

import yaml  # noqa: E402

from cognition.meaning_confirmation import rejection_keys_from_doc  # noqa: E402
from cognition.meaning_proposer import ProposalReport, propose  # noqa: E402
from memory.graph_store import GraphStore  # noqa: E402

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
log = logging.getLogger("propose_meaning_layer")

_DB_PATH = str(PROJECT_ROOT / "data" / "operational_memory.db")
_OUT_YAML = PROJECT_ROOT / "config" / "proposed_meaning.yml"
_OUT_MD = PROJECT_ROOT / "reports" / "meaning_layer" / "derived_proposals.md"
_REJECTIONS = PROJECT_ROOT / "config" / "meaning_rejections.yml"


def _load_rejection_keys() -> set[tuple[str, str]]:
    if not _REJECTIONS.exists():
        return set()
    import yaml as _y
    return rejection_keys_from_doc(_y.safe_load(_REJECTIONS.read_text(encoding="utf-8")) or {})

_YAML_HEADER = (
    "# Proposed meaning-layer entries — DETERMINISTIC PASS (step 1, no LLM)\n"
    "# =====================================================================\n"
    "# Generated by scripts/propose_meaning_layer.py from the observed facts in\n"
    "# graph_store. Every entry is source=\"derived\", status=\"proposed\" — INERT.\n"
    "# Nothing here is active meaning until the operator confirms it and copies the\n"
    "# accepted entries into config/operational_graph.yml.\n"
    "#\n"
    "# Human-confirmed slots were NOT touched. owner_facing is never auto-derived.\n"
    "# This file is the input to the LLM drafter pass.\n"
)


def _build_yaml_doc(report: ProposalReport, generated_at: str) -> dict:
    """Machine-readable proposals: only nodes that actually have a proposal."""
    nodes_out = []
    for n in report.nodes:
        if not n.proposals:
            continue
        nodes_out.append(
            {
                "id": n.builder_node_id,
                "target": n.target_id,
                "proposals": {p.field: p.to_dict() for p in n.proposals},
                "remaining_unknown": n.remaining_unknown,
                "human_confirmed_untouched": n.untouched_human,
            }
        )
    return {
        "version": "1",
        "generated_at": generated_at,
        "generated_by": "scripts/propose_meaning_layer.py",
        "pass": "deterministic",
        "summary": report.summary(),
        "nodes": nodes_out,
    }


def _build_markdown(report: ProposalReport, generated_at: str) -> str:
    s = report.summary()
    lines: list[str] = []
    lines.append("# Meaning-Layer Proposals — Deterministic Pass (step 1, no LLM)")
    lines.append("")
    lines.append(f"_Generated {generated_at} by `scripts/propose_meaning_layer.py`._")
    lines.append("")
    lines.append(
        "Every proposal below is **derived** and **inert** (`status=proposed`). "
        "Nothing is active meaning until you confirm it and copy it into "
        "`config/operational_graph.yml`. Human-confirmed slots were not touched; "
        "`owner_facing` is never auto-derived (left for the LLM/human pass)."
    )
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append(f"- Meaning-layer nodes examined: **{s['meaning_nodes']}**")
    lines.append(f"- Nodes with at least one proposal: **{s['nodes_with_proposal']}**")
    by_field = ", ".join(f"{k} {v}" for k, v in sorted(s["proposals_by_field"].items())) or "—"
    lines.append(f"- Total proposals: **{s['proposals_total']}**  (by field: {by_field})")
    lines.append(f"- Human-confirmed slots left untouched: **{s['human_confirmed_untouched']}**")
    lines.append("")
    lines.append("## Per node")
    lines.append("")

    for n in report.nodes:
        lines.append(f"### `{n.builder_node_id}`  ·  target `{n.target_id}`")
        if n.proposals:
            lines.append("")
            lines.append("**Proposed (derived, inert):**")
            lines.append("")
            for p in n.proposals:
                lines.append(
                    f"- **{p.field}** (`{p.derivation}`, confidence {p.confidence:.2f})"
                )
                lines.append(f"  - value: `{p.value}`")
                lines.append(f"  - evidence: {p.evidence}")
        else:
            lines.append("")
            lines.append("_No facts support a proposal._")
        if n.untouched_human:
            lines.append("")
            lines.append(f"**Human-confirmed (untouched):** {', '.join(n.untouched_human)}")
        if n.remaining_unknown:
            lines.append("")
            lines.append(
                f"**Still unknown → LLM/human pass:** {', '.join(n.remaining_unknown)}"
            )
        lines.append("")

    return "\n".join(lines) + "\n"


def run(dry_run: bool = False, db_path: str = _DB_PATH) -> ProposalReport:
    store = GraphStore(db_path)
    store.connect()
    try:
        nodes = store.get_active_nodes()
        edges = store.get_active_edges()
        annotations = store.get_all_annotations()
    finally:
        store.disconnect()

    rejection_keys = _load_rejection_keys()
    report = propose(nodes, edges, annotations, rejection_keys=rejection_keys)
    s = report.summary()
    rejected_total = sum(len(n.previously_rejected) for n in report.nodes)
    log.info(
        "Deterministic pass: %d meaning nodes, %d proposals across %d nodes "
        "(by field: %s), %d human-confirmed slots untouched, %d previously-rejected skipped%s",
        s["meaning_nodes"], s["proposals_total"], s["nodes_with_proposal"],
        s["proposals_by_field"], s["human_confirmed_untouched"], rejected_total,
        " [DRY-RUN]" if dry_run else "",
    )

    if dry_run:
        for n in report.nodes:
            if n.proposals:
                fields = ", ".join(f"{p.field}({p.derivation})" for p in n.proposals)
                log.info("  [DRY-RUN] %s → %s", n.builder_node_id, fields)
        return report

    generated_at = datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")

    _OUT_YAML.parent.mkdir(parents=True, exist_ok=True)
    doc = _build_yaml_doc(report, generated_at)
    with _OUT_YAML.open("w", encoding="utf-8") as f:
        f.write(_YAML_HEADER)
        yaml.safe_dump(doc, f, sort_keys=False, default_flow_style=False, allow_unicode=True)
    log.info("Wrote %s", _OUT_YAML.relative_to(PROJECT_ROOT))

    _OUT_MD.parent.mkdir(parents=True, exist_ok=True)
    _OUT_MD.write_text(_build_markdown(report, generated_at), encoding="utf-8")
    log.info("Wrote %s", _OUT_MD.relative_to(PROJECT_ROOT))

    return report


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dry-run", action="store_true", help="Print summary, write nothing")
    parser.add_argument("--db", default=_DB_PATH, help="graph_store sqlite path")
    args = parser.parse_args()
    run(dry_run=args.dry_run, db_path=args.db)


if __name__ == "__main__":
    main()
